---
title: "Infant Mortality Rate"
author: "ANTONITO HC"
date: "October 17, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Libraries
```{r Libraries, message=F, warning=F}
library(tidyverse)
library(hrbrthemes)
library(kableExtra)

library(ggplot2)

library(plotly)
```


```{r Infant, message=F, warning=F}

setwd("D:\\akb")

coba <- read.csv("infant.csv", sep = ";")

attach(coba)

head(coba)



p <- coba %>%
  filter(!is.na(IMR)) %>%
  arrange(as.ordered(IMR)) %>%
  mutate(Provinsi = factor(Provinsi, Provinsi)) %>%
  ggplot(aes(x = Provinsi, y = IMR)) +
  labs (title = "Angka Kematian Bayi" , x = " ", y = " ", subtitle = " Angka Kematian Bayi Per 1000 Kelahiran ",
        caption = "Source : Central Bureau Of Statistic (BPS) | Plot generated by : Antonito") +
  geom_bar(stat = "identity", fill = "brown") +
  coord_flip() +
  theme_ipsum()
p

ggplotly(p)


coba %>%
  filter(!is.na(IMR)) %>%
  arrange(IMR) %>%
  mutate(Provinsi=factor(Provinsi, Provinsi)) %>%
  ggplot(aes(x = Provinsi, y = IMR)) +
  labs(title = "Angka Kematian Bayi" , x = " ", y = "Kematian Per 1.000 Kelahiran Hidup ", subtitle = "Provinsi dengan Angka Kematian Bayi Tertinggi",
       caption = "Source : Central Bureau of Statistic (BPS), 2016 | Plot generated by : Antonito") +
  geom_bar(stat = "identity", fill = "brown") +
  coord_flip() +
  theme_ipsum() +
  theme(panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        legend.position = "none") 


tmpp <- coba %>%
  filter(!is.na(IMR)) %>%
  arrange(desc(IMR)) %>%
  mutate(Provinsi = factor(Provinsi, Provinsi))

tmpp

kematian = read.csv("bayi.csv", sep = ";")


p2 <- kematian %>%
  filter(!is.na(AKB)) %>%
  arrange(as.ordered(AKB)) %>%
  mutate(Wilayah = factor(Wilayah, Wilayah)) %>%
  ggplot(aes(x = Wilayah, y = AKB)) +
  labs (title = "Angka Kematian Bayi Jawa Timur" , x = " ", y = "Kematian Per 1.000 Kelahiran Hidup ", subtitle = " Angka Kematian Bayi Per 1000 Kelahiran ",
        caption = "Source : Central Bureau Of Statistic East Java (BPS) | Plot generated by : Antonito") +
  geom_bar(stat = "identity", fill = "tomato4") +
  coord_flip() +
  theme_ipsum()
p2

ggplotly(p2)


k = kematian %>%
  filter(!is.na(AKB)) %>%
  arrange(AKB) %>%
  mutate(Wilayah=factor(Wilayah, Wilayah)) %>%
  ggplot(aes(x = Wilayah, y = AKB)) +
  labs(title = "Angka Kematian Bayi" , x = " ", y = "Kematian Per 1.000 Kelahiran Hidup ", subtitle = "Kabupaten/Kota dengan Angka Kematian Bayi Tertinggi di Jatim",
       caption = "Source : Central Bureau of Statistic (BPS) East Java, 2016 | Plot generated by : Antonito") +
  geom_bar(stat = "identity", fill = "steelblue4") +
  coord_flip() +
  theme_ipsum() +
  theme(panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        legend.position = "none") 

k

ggplotly(k)




```

